
---------------------------------------

Lecture du document à traiter : Début
Lecture du document à traiter : Fin.

---------------------------------------

Vérification du document à traiter : Début
Vérification du document à traiter : Fin.

---------------------------------------

Initialisation de la machine : Début
Initialisation de la machine : Fin.

---------------------------------------


Génération du fichier Code CN : Début

Information : ** activité Programme de fabrication.1 : DEBUT. ** 

Information : ** activité Côte.1 : DEBUT. ** 
Attention, L'activité Côte.1 n'est pas à jour.
Information: L'activité Côte.1 a été mise à jour.
Information : ** Temps d'usinage et total : 2s , 2s. ** 
Information : ** activité Côte.1 : FIN  . ** 
Information : ** activité Programme de fabrication.1 : FIN  . ** 
Génération du fichier Code CN : Fin.

---------------------------------------


---------------------------------------

Fin du Batch.

---------------------------------------

